name: ${project.name}
version: ${project.version}
author: ${project.author}
main: com.winterhavenmc.deathcompass.PluginMain
api-version: 1.16
softdepend: [Multiverse-Core]

commands:
  deathcompass:
    description: show DeathCompass settings or reload configuration file
    usage: /deathcompass [command]
    permission-message: You don't have the required <command> permission.

permissions:
  deathcompass.use:
    description: Give player a compass on death and set compass target to last death location
    default: true
        
  deathcompass.help:
    description: View DeathCompass help
    default: op

  deathcompass.reload:
    description: Reload DeathCompass config file
    default: op

  deathcompass.status:
    description: View DeathCompass settings
    default: op

  deathcompass.admin:
    description: DeathCompass admin commands
    default: op
    children:
      deathcompass.help: true
      deathcompass.status: true
      deathcompass.reload: true
